# Generated by Django 5.1.3 on 2024-12-01 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0004_calculations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
