# Generated by Django 5.1.3 on 2024-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0007_alter_user_bio_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='data_calculation_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
