# Generated by Django 5.1.3 on 2024-12-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0008_calculations_data_calculation_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='data_calculation_img',
        ),
    ]
