# Generated by Django 5.1.3 on 2024-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0011_alter_contactus_options_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
