# Generated by Django 5.1.3 on 2024-12-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0012_contactus_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser_name', models.CharField(max_length=100, verbose_name='Superuser Name')),
                ('reply_message', models.TextField(verbose_name='Reply Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Replied At')),
                ('contact_us_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='circuits.contactus', verbose_name='Contact Query')),
            ],
            options={
                'verbose_name': 'Reply to Query',
                'verbose_name_plural': 'Replies to Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
