# Generated by Django 5.1.3 on 2024-12-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0013_replycontactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyContactUs',
        ),
    ]
